### ISSUE TITLE
No possibility to overwrite "ROOT_ORGANIZATION_ID" in some functions

### ISSUE THREAD

**Issue by BenLinnik** [sonatype-nexus-community/iq-config-as-code#1]
https://github.com/sonatype-nexus-community/iq-config-as-code/blob/84167878d62b7212b0c9ac5e86eeee6d348e0dc0/iq-apply-conf.py#L239
https://github.com/sonatype-nexus-community/iq-config-as-code/blob/84167878d62b7212b0c9ac5e86eeee6d348e0dc0/iq-apply-conf.py#L365

seems not correct, please see your [documentation](https://help.sonatype.com/iqserver/automating/rest-apis/organization-rest-apis---v2#OrganizationRESTAPIs-v2-GetOrganization). 

It probably should be `url = f'{iq_url}/api/v2/applicationCategories/organization/{org}'`, but you will have to pass the `org` parameter as in the other functions :)

**UPDATE**: I just realized, it is maybe intended as `ROOT_ORGANIZATION_ID` is a valid value, see https://community.sonatype.com/t/how-to-retrieve-a-list-of-iq-server-roles-and-associated-users/552/2. Haven't seen it in the documentation, but as a default variable value and was confused. In this case, nevermind, sorry for reporting :) Please close this report then 👍

**Comment by CSMonkee** [comment]
Thanks for your observation. The set_categories function is designed to GET the global application categories upon initialisation. The application_categories function is used to persist application categories scoped to a child organisation, when they are parsed from the JSON config data.
